### ISSUE TITLE
CSS things like text-shadow and blur not working?

### ISSUE THREAD

**Issue by ryancole** [obsproject/obs-browser#100]
Hello,

I've got some CSS like `text-shadow` and also tried `filter: blur` but they don't appear to render on the obs-browser source.

Is there a limitation on these types of styles?

Thanks!

**Comment by DDRBoxman** [comment]
Currently, the browser source ships with GPU disabled due to a performance issue in CEF which can cause issues like this. Recently CEF merged a fix to try to mitigate this once that version of CEF is finalized we can try enabling GPU again and see if there are still performance issues.

**Comment by ryancole** [comment]
Thanks, @DDRBoxman. Do you happen to know which version of CEF merged this fix, or have a link to the patch?

I've like to follow that build of CEF so that I can watch obs browser to see when it lands in the browser.

Thanks!

**Comment by skovacs1** [comment]
@ryancole I'm not DDRBoxman, but based on my reading, disable-gpu was set was due to some serious issues with off-screen rendering.

Based on the information at hand and the timing, my guess is that DDRBoxman may have been referring to the solution for CEF issue 2046 which was merged in CEF master revision 4c795f5 and **3239** branch revision 8f2fa99. That really just addresses a low-hanging fruit of the massive cluster of issues that is rendering in CEF.

Per comments, there are still some demonstrable issues with v-sync, OSR framerate, CEF's render pipeline leading to frame latency, and, as always, client-specific optimization. This change was mostly only a demonstrable improvement on some powerful machines so I don't think this is the holy grail solution that everyone has been hoping for, but it's certainly worth checking out when that CEF is finalized.
