### ISSUE TITLE
Poor performance / CSS transition

### ISSUE THREAD

**Issue by elbarto132** [obsproject/obs-browser#104]
I'm using OSX High Sierra and a MBP 15" 2017 with OBS Studio
I have a Browser Source with a HTML site which connects to a Websockets Server and if triggered by a specific message it displays a CSS transition (just 2 divs floating from bottom to top using an "ease" transition).
As soon as this transition starts the CPU usage of CEF goes to 100% and finishes as soon as the CSS transition is done.
So somehow this CSS transition is using a very high amount of CPU performance. Is this a general problem or just a Mac problem?

**Comment by DDRBoxman** [comment]
Currently, GPU is disabled for the browser source due to issues in CEF. So Chrome is using the software renderer which will eat up a bunch of CPU. 

https://github.com/kc5nra/obs-browser/issues/45

**Comment by Diellan** [comment]
CEF fixed several of these issues in September, is it time to readdress this?

**Comment by ohcibi** [comment]
The settings window in OBS has a a 'enable hardware acceleration for browser source'-checkbox. Am I correct that this checkbox simply does nothing currently instead of being removed or disabled because of this issue?

**Comment by OsirisNL** [comment]
See my reply above yours, so that checkbox definitely does something.

**Comment by ohcibi** [comment]
@Osiris I’m asking because the performance of my css transitions in my browser sources is poor although that thing is checked. I even see that the obs browser process runs on my gpu but still the performance sucks. It runs fine in slobs which also runs on the gpu. I guess because it is an electron app. So the chromium embedded bugfix alone don’t seem to be a fix for this issue right here.

**Comment by DDRBoxman** [comment]
#149
