### ISSUE TITLE
Latest OBS Update (21.1.0) breaks many previously-working browser sources

### ISSUE THREAD

**Issue by DivineJayce** [obsproject/obs-browser#112]
To put it simply, upon updating to this version with the new Chromium version I was met with all browser sources proceeding to fail including:

(http://) NightDev Chat
(https://) Streamlabs Alerts
(file:///) My local Flash overlay

After a bit of fiddling I found that in previous versions when I had copied the URLs into the URL field OBS was automatically removing "http://" and "https://" from the address which worked fine up until the latest update. I had to manually go back into each source and add these schemes before the sources would work again. I feel most people who are experiencing this issue wouldn't think to do it so I still see it as an issue regardless.

All of this worked fine for my web-based URLs but the same couldn't be said for my local Flash overlay. I use the "file:///" scheme instead of checking the "Local File" box and referencing the page directly because Flash behaves differently in-browser depending on how it's loaded and using file:/// was the only thing that worked.

Is there a way to access the browser settings so that I can manually change some of these behaviours myself? Is the file:/// scheme or flash being disabled in some way? I'm fearful that I won't be able to update my streaming software anymore if my content requires a legacy version of the browser.

**Comment by WizardCM** [comment]
Not sure about the protocol removal (my understanding is it uses the input box as-is and doesn't remove protocols, but I do have a suggestion for Flash.

Try launching OBS with the `--allow-file-access-from-files` flag. Note that OBS passes on any Chrome/CEF related flags to the browser source as-is. Is your flash overlay the flash file directly, or a webpage containing the flash file? This should fix the latter, but otherwise I'm not seeing a flag to enable flash - only to disable it. You should be avoiding Flash in 2018 anyway, but OBS/CEF shouldn't be stopping you from using it.

You can also enable the `--remote-debugging-port=9222` flag and launch `http://localhost:9222` to see what error you're getting in the console.

**Comment by DivineJayce** [comment]
Thanks! --allow-file-access-from-files seems to have done the trick in this case.

I had worked out to do --enable-media-stream for authorising webcam and microphones for alternative uses in the past but had hit a roadblock with this. Really appreciate it!

I would gladly move away from Flash except I also use it to draw and animate. It works fine when running as its own standalone thing but obviously adding browsers to the mix complicates it a bit more.

Still, this and your other advice should keep me going for a long time now, thanks again!
