### ISSUE TITLE
How to enable "Experimental Web Platform features"?

### ISSUE THREAD

**Issue by Jorys-Paulin** [obsproject/obs-browser#115]
I need to enable these to use the `backdrop-filter` property. Does the CEF even support these?

**Comment by CoDEmanX** [comment]
Chrome doesn't officially support it yet: https://bugs.chromium.org/p/chromium/issues/detail?id=497522
It is available if you enable the Experimental Web Platform features, but it seems like they dropped the vendor prefix meanwhile - so make sure you use the unprefixed name in CSS and JS, or you may get fooled and think that it doesn't work:

- `backdrop-filter` instead of `-webkit-backdrop-filter` in CSS
- `style.backdropFilter` instead of `style.WebkitBackdropFilter` in JS

Start OBS with the command line parameter `--enable-experimental-web-platform-features`, then use this as URL for the browser source for testing: https://codepen.io/simran/pen/oPXewY

![grafik](https://user-images.githubusercontent.com/1309249/44495408-1f829680-a670-11e8-9c46-086daaf460a8.png)

**Comment by Jorys-Paulin** [comment]
@CoDEmanX Tested and working also on my OBS. The example works as expected, but I tested to see if blurring what's behind the actual source was supported but it seems it's not. I guess it's not implemented yet in Chrome or CEF. Thanks a lot for the response!

**Comment by Lange** [comment]
@Jorys-Paulin It is not possible for a browser source to blur content behind it. Doing so would require the browser source to be able to sample the pixels underneath it in OBS, which would require substantial changes to both OBS and Chromium to enable.
