### ISSUE TITLE
Cannot use user media devices without flag

### ISSUE THREAD

**Issue by hunterpollpeter** [obsproject/obs-browser#146]
No way to get access to user media devices (webcams and microphones) without having to use flag. Added a flag in PR #143. Would love to see this in the next release.

**Comment by mnill** [comment]
Any chances to be merged?

**Comment by RytoEX** [comment]
Chromium/Chrome/CEF by default will prompt users for permission to use audio/video devices.  This permission prompt can be bypassed by passing the `--use-fake-ui-for-media-stream` flag to Chromium/Chrome/CEF.  Since we pass all user-specified flags to CEF, users can pass this flag to OBS to bypass the permissions prompt.

As we regard this to be unsafe default behavior, we will not add this to OBS as the default behavior.  Furthermore, we don't consider this to be a bug, so I'll be closing this issue.  For more information on our reasoning, see comments on #143.
