### ISSUE TITLE
ES6 Modules won't load from local files

### ISSUE THREAD

**Issue by Akkuma** [obsproject/obs-browser#180]
Currently, if you try to use a local file with es6 modules you'll have nothing work as it requires disabling the same origin policy. Is it possible for OBS to opt into this flag potentially for only local files, so it isn't required from the shortcut?

**Comment by Lange** [comment]
Chiming in as someone who uses `obs-browser` a lot but is not a maintainer of it: I think the answer to this issue comes down to what the maintainers want the philosophy of `obs-browser` to be. Specifically, if they want to go the extra mile to support workflows based on local files, or if they want to stick to normal browser behavior and encourage all users to use a small local webserver of some kind, of which there are many easy great choices available.

My personal vote is that `obs-browser` not keep making changes to support local files, because there are genuine security concerns with turning off all of these protections. Instead, perhaps the README could be updated with some examples on how to run a small, local, lightweight webserver?

**Comment by WizardCM** [comment]
I also agree that if you need advanced functionality, a simple web server will do the job. Sacrificing security in favour of advanced features is not a road I'd like to see us go down.

For example: `python -m http.server 8000` in your working directory.
