### ISSUE TITLE
Compiling OBS Browser?

### ISSUE THREAD

**Issue by NCommander** [obsproject/obs-browser#20]
I've tried to build OBS browser from scratch with no success; apparently caused by C runtime mismatches, or an issue with the version of CEF I'm using. I'm trying to build the CEF browser plugin with inclusion with a custom build of OBS called Tachyon (https://github.com/WatchBeam/ftl-studio) so I can include it as part of the 'out of the box' experience; the pre-existing binary does work, but I'm not sure I can freely redistribute that.

Is there a step-by-step guide for getting the plugin built on Windows?

**Comment by Draygera** [comment]
Interesting seeing you here today, @NCommander. I'm wondering the same thing, myself

**Comment by Draygera** [comment]
Ok, so first of all, you'll need to make sure you have everything required on this page (Visual Studio 2015 with Update 2 and required tools listed): https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md

And then checkout this page: https://www.chromium.org/developers/how-tos/install-depot-tools

But it doesn't tell exactly what all you're supposed to do to build on there.

Step by step build instructions from my own messing around and looking around on google (mind you this is incomplete and I'm still having some issues building but slowly working through them):

1. Either download the zip version or git version of the depot_tools (I used the git version as instructed underneath the Linux / Mac header)

2. Go into the depot_tools folder and run "gclient config https://chromium.googlesource.com/v8/v8". That will download everything necessary to build the depot_tools lib but not chromium yet. The next step is really important.

3. Run: "gclient sync". This will download and attempt to build the chromium version listed above. It's definitely needed.

I'm on Windows 10 64-bit and will keep posting more info as I go.

**Comment by Draygera** [comment]
Ok, to bypass the whole chromium dev credetials thing, all you have to do is follow the instructions here: https://chromium-review.googlesource.com/new-password

**Comment by NCommander** [comment]
I did manage to get this to compile using the pre built CEF binaries from
Google with vs2013 update 5. I needed the current head and to use the
static build options in the plugin to get it to link. I can post more
detailed instructions later.
Michael

**Comment by Draygera** [comment]
Sorry. I was derping hard but I'm currently doing the same thing myself. I deleted the last two posts because I figured it out myself but instead am building cef from source. :D

**Comment by NCommander** [comment]
Building chromium from source? You must like pain. As a note both tachyon
and upstream obs use vs2013. At only recently got an update to enable
vs2015. I don't think anyone has built it with that and you might have
strange issues

**Comment by Draygera** [comment]
Probably. But you don't know pain until you've got through the entire Linux from Scratch process. Build a toolchain to build the main toolchain so you can build another toolchain so you can build the entire OS from source. :O

**Comment by NCommander** [comment]
I worked on porting ubuntu to ARM and AArch64. I've built Ubuntu from
source more than once with custom tool chains ;)

**Comment by Draygera** [comment]
I did that stuff because I was curious and bored. I'm not much of a dev at the moment but I can pretty build anything from source if needed.

**Comment by Draygera** [comment]
Only porting I ever attempted was Shadowgrounds to SDL2. My repo is still on here but I never fully got it working right. It compiles and runs but the actual game is unplayable.

**Comment by mzmiric5** [comment]
@NCommander you mentioned earlier that you can post more detailed instructions later, any chance of a quick write up on that or?

**Comment by CoDEmanX** [comment]
Here's what I did on Windows 10:

1. Cloned this repository into the plugins folder of my obs-studio working copy (...\OBS\obs-studio\plugins\obs-browser)

2. Downloaded pre-built CEF from https://cefbuilds.com/ (the most recent branch, currently 2704). Dev channel (trunk) did not compile because it seemed to lack at least one feature that was probably added between that version and the latest branch.

3. Unpacked CEF: ...\OBS\obs-studio\plugins\obs-browser\cef

4. Configured and generated cef to order to build the wrapper library with **cmake-gui** (64bit / Win64 compiler):
Source: .../OBS/obs-studio/plugins/obs-browser/**cef**
Build dir: .../OBS/obs-studio/plugins/obs-browser/**cef/build**

5. Opened ...\OBS\obs-studio\plugins\obs-browser\\**cef\build\cef.sln** with Visual Studio (2013 or 2015) and compiled the **libcef_dll_wrapper** target on *Release* configuration.

6. Opened ...\OBS\\**obs-studio\plugins\CMakeLists.txt** and added *obs-browser* at the bottom to include it in the builds of obs-studio: `add_subdirectory(obs-browser)`

7. Configured and generated *obs-studio* with **cmake-gui** (64bit / Win64 compiler), providing some additional variables:
Source: .../OBS/obs-studio
Build dir: .../OBS/obs-studio/build

  - `CEFWRAPPER_LIBRARY` = .../OBS/obs-studio/plugins/obs-browser/cef/build/libcef_dll_wrapper/**Release/libcef_dll_wrapper.lib**
  - `CEF_INCLUDE_DIR` = .../OBS/obs-studio/plugins/obs-browser/**cef**<br>
  *(Note: do not set this to /obs-browser/cef/include !)*
  - `CEF_LIBRARY` = .../OBS/obs-studio/plugins/obs-browser/cef/**Release/libcef.lib**

8. Opened ...\OBS\obs-studio\\**build\obs-studio.sln** with Visual Studio and compiled the **ALL_BUILD** target on *Release* configuration

9. Copied the **content** of ...\OBS\obs-studio\plugins\obs-browser\\**cef\Resources** into ...\OBS\obs-studio\build\rundir\Release\obs-plugins\64bit

10. Copied the **content** of ...\OBS\obs-studio\plugins\obs-browser\\**cef\Release** into ...\OBS\obs-studio\build\rundir\Release\obs-plugins\64bit (*.lib and AFAIK widevinecdmadapter.dll can be omitted)

11. Optionally downloaded and unpacked the Release debug symbols for CEF into above directory as well (libcef.dll.pdb).

12. Ran ...\OBS\obs-studio\build\rundir\Release\bin\64bit\\**obs64.exe** and added a BrowserSource source.

I experienced some issues using it on one of my computers (unexpected shutdowns), but not sure what is causing it. It worked pretty well on another machine. Running the *obs* target of obs-studio.sln in Visual Studio with the debugger attached and using the Debug version of CEF, you will most certainly see it stop at some breakpoints and can just click continue. If you play a video through the source like youtube and quit OBS, there seems to be a race condition which can lead to access violations or NULL pointer derefs so it seems. Does not occur on all machines though.

**Comment by olegchir** [comment]
Is it an expected behavior that all breakpoints in Visual Studio never triggered, with description: "The breakpoint will not currently be hit. No symbols have been loaded for this document"

Screenshot: http://imgur.com/6fY44S4

Brekpoints in standard plugins like obs-text are triggered ok

**Comment by shadow0162** [comment]
@olegchir I got the same problem with you. Do you solve it ?

**Comment by CoDEmanX** [comment]
IIRC that is normal.

BTW: cefbuilds.com does not provide the new minimum required CEF version 288x, but you can find it here: http://opensource.spotify.com/cefbuilds/index.html

**Comment by olegchir** [comment]
@shadow0162 still no solution

@CoDEmanX If this is normal, how to develop without debugging? Do you have to observe using some kind of special telepathy to see the errors through time, space and broken breakpoints?

**Comment by OsirisNL** [comment]
obs-browser-facade does nothing.

**Comment by MinaRoss** [comment]
OBS complied with MD. Is obs-browser complied with MT or MD?

**Comment by pantonvich** [comment]
I downloaded cef_binary_3.2987.1601.gf035232_windows64 and compiling under vs2013 get the following in obs-studio for obs-browser:

`1>MSVCRT.lib(MSVCR120.dll) : error LNK2005: memmove already defined in LIBCMT.lib(memcpy.obj)
1>MSVCRT.lib(MSVCR120.dll) : error LNK2005: _dclass already defined in LIBCMT.lib(nan.obj)
1>MSVCRT.lib(MSVCR120.dll) : error LNK2005: fclose already defined in LIBCMT.lib(fclose.obj)
1>MSVCRT.lib(MSVCR120.dll) : error LNK2005: fopen already defined in LIBCMT.lib(fopen.obj)`

**Comment by MinaRoss** [comment]
@pantonvich I have met same problem and solved. cef_binary_3.2987.1601.gf035232_windows64 config Property Pages -> C/C++->Code Generation, set /MD, and rebuild. Configured and generated obs-studio with cmake-gui, add additional entry USE_STATIC_CRT = false.

**Comment by CoDEmanX** [comment]
I did not see above problems with VS2015, but ran into other problems:

- CEF builds newer than 3.2987 don't appear to work because of some API changes, not sure how to adjust it.
- Using the 2987 branch, there are no issues with CEF itself, but multiple errors about unresolved external symbols, all related to jansson.lib

| symbol | in function | project | file |
|---|---|---|---|
| __imp_fgetc | json_loadf | cef-bootstrap | jansson.lib(load.obj) |
| __imp_fopen | json_load_file | cef-bootstrap | jansson.lib(load.obj) |
| __imp__time64 | json_object_seed | cef-bootstrap | jansson.lib(hashtable_seed.obj) |
| __imp_strncpy | hashtable_set | cef-bootstrap | jansson.lib(hashtable.obj) |
| __imp_strtod | jsonp_strtod | cef-bootstrap | jansson.lib(strconv.obj) |
| __imp_qsort | do_dump | obs-browser | jansson.lib(dump.obj) |
| __imp__time64 | json_object_seed | obs-browser | jansson.lib(hashtable_seed.obj) |
| __imp_strncpy | hashtable_set | obs-browser | jansson.lib(hashtable.obj) |
| __imp_strtod | jsonp_strtod | obs-browser | jansson.lib(strconv.obj) |

**Comment by pkviet** [comment]
@CoDEmanX 
ran into the same jansson errors on VS 2015 until I followed your set of instructions AND the tweaks given by MinaRoss: USE_STATIC_CRT = false & set /MD for the libcef_dll_wrapper project

**Comment by computerquip-streamlabs** [comment]
This issue is quite old and was useful for awhile but it's outdated. The info here is no longer of use. You can build libcef with `-DCEF_RUNTIME_LIBRARY_FLAG="/MD"` to dynamically-link the run-time. The other issues also don't appear to be an issue anymore.
