### ISSUE TITLE
browser source on linux dont show up

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-browser#214]
I read post on bazukas page, and he said that "Good news! Starting with version 25, OBS Studio ships with browser source that work on Linux. I recommend you to use that and report any issues at obs-browser repo and/or official discord community." I have debian bullseye with latest updates and and obs version 25.0.3 dfsg1-2 and i dont have prebuit-in broswer source in obs studio. Is there another obs 25 with browser source for linux? I cant use bazukas browser for obs cuz i my obs crush and my system freeze and only hard reset save my pc from freeze. Can you help me pls?

**Comment by WizardCM** [comment]
Debian packages of OBS are not built by us. You will need to contact whoever maintains the debian package to build & include CEF 3809.

**Comment by koreanfan** [comment]
if i build obs-studio from source, browser source shows up?

**Comment by WizardCM** [comment]
If you follow the instructions for building obs-browser and obs-studio, yes the browser source should appear.

**Comment by walterav1984** [comment]
It's the same issue for ubuntu 20.04 focal fossa which imports debian testing releases. @koreanfan I can confirm that building obs-studio git master on ubuntu 20.04 gives a workable option for browser source, however without video support!

Since the default obs-studio build instructions use a pre-build CEF version (which may not be shipped with video codec support because of license issues) the next step is build your own version of CEF before you build obs-studio. Building obs-studio is fast and easy building CEF takes a lot more time and effort.

Debian maintainers could not handle the burden of maintaining the CEF code (on which browser plugin is based), since it is huge and needs the attention and security fixes like other webbrowsers (firefox/chromium). As a consequence debian builds software packages like obs-studio / nageru / casparcg-server without browser support at all...

**Comment by tvvignesh** [comment]
Facing the same issue on my end. Maybe it can be shipped as a snap, AppImage or something similar to avoid such issues? Just saying.

**Comment by Gol-D-Ace** [comment]
@walterav1984 Debian build is missing in general everything that relies on submodules and therefore would in it's current state never include the browser source anyways because of that.

For example FTL support is entirely missing because of this and in the future VST will join.

**Comment by tvvignesh** [comment]
Actually more than all of these, the most reliably working option is the snap from snapcrafters: https://github.com/snapcrafters/obs-studio

**Comment by Gol-D-Ace** [comment]
Which is avoiding the issue by using the Qt file dialog which we are trying to avoid because it lacks functionality.

**Comment by tvvignesh** [comment]
If I use animated overlays, I am getting a lot of stutter both in OBS snap as well as building it directly. Is there a way to either avoid it or go with some other browser like firefox. It may be because of hardware acceleration, is there a way to fix it? It works perfectly if I open the same url in either chrome or chromium for firefox directly and so, its may be issue with CEF in linux. Not sure.

@Gol-D-Ace Any tips?
