### ISSUE TITLE
Intermittent audio stuttering when using the "Control audio via OBS" feature

### ISSUE THREAD

**Issue by NarryG** [obsproject/obs-browser#237]
When using the "control audio via obs" feature of the plugin, audio will occasionally stutter. The stutter isn't completely reliable, but happens enough to be an issue that can damage the user experience when using the feature.  
If this feature is disabled, the audio plays back reliably with no stuttering.

## Platform
Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior
Audio played back through the browser source should play consistently without pops/stutters

## Current Behavior
Audio played back through the browser source will sometimes pop/stutter
https://obsproject.com/logs/GiwJKg9EK12-tPvg

## Steps to Reproduce
1. Create an empty scene
2. Add a browser source
3. Add the default Streamlabs notification as the URL
4. Click "Control audio via OBS"
5. Click the notification preview button on the Streamlabs website until stutter occurs.

Video demonstrations:  
- https://streamable.com/2ehb3f  
- https://twitter.com/DesertPogona/status/1277730727833018373

## Additional information  
Forum post with similar issue:  
https://obsproject.com/forum/threads/weird-glitchy-audio-from-browser-source-when-using-control-audio-via-obs.116648/

This was brought up on Discord and it was stated it'd most likely be fixed when CEF is updated. 
> pkv  Today at 3:51 PM
> There will be a new audio API used for browser source. Might work better. I'm not sure there's currently a straightforward solution to your issue. No eta though on when we'll use this new cef api because we're waiting for some other features to be merged in cef
> pkv   Today at 4:03 PM
> I'll keep that in mind though to check with new cef
> Post an issue documenting repro steps.

**Comment by desertpogona** [comment]
I have this problem and really hope this gets fixed at some point. It's the only thing preventing me from using the browser source's audio playback

**Comment by marcmagus** [comment]
I am also suffering from this issue, on Linux, and unsurprisingly it persists in v26.0.2. Control audio would be extremely helpful as different browser sources to not distinguish themselves in PulseAudio so levels cannot be set and retained properly.

**Comment by b0ses** [comment]
Been dealing with this issue since the BrowserSource enabled "Control Audio via OBS". Workaround is having the link open in another browser and managing the browser's audio though I'd much prefer working with the BrowserSource and OBS.

**Comment by JillKatze** [comment]
This bug has been driving me up a wall for ages so I did some digging and I believe it's caused by the problem described [in this BitBucket issue](https://bitbucket.org/chromiumembedded/cef/issues/2995/audio-capture-susceptible-to-packet-loss).

It appears that the exact change pointed out in that BitBucket issue was recently (~2 months ago) integrated into Chromium as a fix for [this Chromium bug (1130375)](https://bugs.chromium.org/p/chromium/issues/detail?id=1130375). Once OBS Browser updates to a CEF version with that fix, I'd bet this issue will clear up.

[Updating CEF on Windows is on the near-term OBS roadmap](https://github.com/obsproject/obs-studio/discussions/3853) and I'd love it if a version with that fix got pulled in.

**Comment by RytoEX** [comment]
We have completed our upgrade to CEF 4638 (Chromium 95) which looks to me like it includes the upstream Chromium fixes [linked to above](https://github.com/obsproject/obs-browser/issues/237#issuecomment-834249813).  We plan to ship this upgrade with OBS Studio 27.2, which is currently in beta.  The beta releases can be found on the [obs-studio GitHub releases page](https://github.com/obsproject/obs-studio/releases).  Could those affected by this issue test and report whether or not this issue is resolved?  Thanks!

**Comment by b0ses** [comment]
Tested on a stream last night and it worked like a charm 👍 . I spammed a bunch of sounds and didn't notice any clipping/lagging/buzzing.

**Comment by RytoEX** [comment]
Original reporter confirmed on Discord that this Issue has been resolved.

**Comment by NarryG** [comment]
I can confirm that after testing between both me and a friend who struggled with this issue, neither of us experience it after the CEF upgrade.

**Comment by Svenja001** [comment]
Hi, I also have this Issue with both my Browsersources on my new PC. I am glad not to be the only one, first I thought I broke something by importing the Settings from my old Laptop, but new Configuration didn't change anything so I started to search more intensively and finally found this Issue.

**Comment by gnkidwell** [comment]
This issue is occurring in OBS 28 as well… something must have recently changed…

**Comment by pkviet** [comment]
> This issue is occurring in OBS 28 as well… something must have recently changed…

please open a new issue with logs which will allow us to see your specific setup.

**Comment by ppumkin** [comment]
Hello is there a new issue opened for this? I have been searching and it seems like a reoccurring problem 
ref
https://obsproject.com/forum/threads/weird-glitchy-audio-from-browser-source-when-using-control-audio-via-obs.116648/#post-594506

**Comment by pkviet** [comment]
> Hello is there a new issue opened for this? I have been searching and it seems like a reoccurring problem 
> ref
> https://obsproject.com/forum/threads/weird-glitchy-audio-from-browser-source-when-using-control-audio-via-obs.116648/#post-594506

Open your own issue with log.
The original issue was solved for the OP by a subsequent upgrade of cef. Since then we have again updated cef to version 5060.
It'd be helpful to know if your issue is in the recording or only heard on monitoring (which would point the issue to the monitoring device drivers).

**Comment by phillypro** [comment]
> > Hello is there a new issue opened for this? I have been searching and it seems like a reoccurring problem
> > ref
> > https://obsproject.com/forum/threads/weird-glitchy-audio-from-browser-source-when-using-control-audio-via-obs.116648/#post-594506
> 
> Open your own issue with log. The original issue was solved for the OP by a subsequent upgrade of cef. Since then we have again updated cef to version 5060. It'd be helpful to know if your issue is in the recording or only heard on monitoring (which would point the issue to the monitoring device drivers).

for me and most likely for others the issue only occurs when the obs window is not in focus
when you minimize or click off to another window from obs the stuttering begins on browser audio sources
if you are focused on obs all is fine ......this is on a pc with 128bg ddr5  geforce 4090 i9 13900k

**Comment by Svenja001** [comment]
I opened a new Issue, it was just able to reproduce it today. #405

**Comment by ppumkin** [comment]
When we moved to another PC the problem went away. Not sure why but on laptop it did this randomly. And on newer PC always find
