### ISSUE TITLE
Not compilable against newer versions of CEF

### ISSUE THREAD

**Issue by JoshStrobl** [obsproject/obs-browser#298]
### Operating System Info

Other

### Other OS

Solus (Linux)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

Not Applicable

### Expected Behavior

obs-browser in obs-studio 27.0.1 be compilable against CEF 91+

### Current Behavior

Compilation error due to removed `web_security` per https://bitbucket.org/chromiumembedded/cef/issues/3058/remove-cefbrowsersettingsweb_security

```
/home/build/YPKG/root/obs-studio/build/obs-studio.git/plugins/obs-browser/obs-browser-source.cpp: In lambda function:
/home/build/YPKG/root/obs-studio/build/obs-studio.git/plugins/obs-browser/obs-browser-source.cpp:184:23: error: ‘CefBrowserSettings’ {aka ‘class CefStructBase<CefBrowserSettingsTraits>’} has no member named ‘web_security’
  184 |    cefBrowserSettings.web_security = STATE_DISABLED;
```

### Steps to Reproduce

1. Compile latest cef-minimal (e.g. 91.1.16/17) from https://cef-builds.spotifycdn.com/index.html
2. Compile obs-studio 27.0.1 against new cef-minimal
3. See FTBFS.

**Comment by WizardCM** [comment]
Correct, we officially support 75, 85 and 87 at the moment. These can be found on the [Spotify CEF CDN](https://cef-builds.spotifycdn.com/index.html).

There's already a PR for another change related to 91 at #297.

Feel free to submit a PR to use the `--disable-web-security` command line flag rather than `cefBrowserSettings.web_security`.
